require("dotenv").config();

module.exports = {
  PORT: process.env.PORT || 5000,

  REDIS_HOST: process.env.REDIS_HOST,
  REDIS_PORT: process.env.REDIS_PORT,

  UPSTREAM_URL: process.env.UPSTREAM_URL,

  RATE_LIMIT_CAPACITY: parseInt(process.env.RATE_LIMIT_CAPACITY),
  RATE_LIMIT_REFILL_RATE: parseInt(process.env.RATE_LIMIT_REFILL_RATE),

  CIRCUIT_BREAKER_FAILURE_THRESHOLD: parseInt(process.env.CIRCUIT_BREAKER_FAILURE_THRESHOLD),
  CIRCUIT_BREAKER_RESET_TIMEOUT_SECONDS: parseInt(process.env.CIRCUIT_BREAKER_RESET_TIMEOUT_SECONDS),
  CIRCUIT_BREAKER_HALF_OPEN_SUCCESS_THRESHOLD: parseInt(process.env.CIRCUIT_BREAKER_HALF_OPEN_SUCCESS_THRESHOLD),
};